name: Create Standalone Executable
on:
  push:
    tags:
      - "v2*"
  workflow_dispatch:
env:
  LINUX_NAME: vyxal-linux
  WINDOWS_NAME: vyxal-windows
  MACOS_NAME: vyxal-macos
jobs:
  make-the-stuff:
    name: Generate executable for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            exe-name: vyxal-linux
    steps:
      - name: Clone Vyxal repository
        uses: actions/checkout@v2
        with:
          repository: Vyxal/Vyxal
          ref: main
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Pip install requirements
        run: pip install .
      - name: Install pyinstaller
        run: pip install pyinstaller
      - name: Run pyinstaller
        run: |
          pyinstaller vyxal/__main__.py --name vyxal2
      - name: Add vyxal2 to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/vyxal2
